apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: us-central1-docker.pkg.dev/sit737-24t1-pansuria-ba73c9a/quickstart-docker-repo/node-web
        ports:
        - containerPort: 80 
